glitch-escape/glitch-escape

Assets/GlitchEscape/Scenes/Testing/main.unity, Assets/GlitchEscape/Scripts/Player/Controls/PlayerControls.cs, Assets/GlitchEscape/Scripts/UI/HUD.cs
Made camera further to the player
The player always respawn to the last saved point
=> Camera and respawn

Assets/GlitchEscape/Config/Input/Input.cs, Assets/GlitchEscape/Config/Input/Input.inputactions, Assets/GlitchEscape/Scenes/Testing/main.unity, Assets/GlitchEscape/Scripts/Player/Controls/PlayerControls.cs, ProjectSettings/TagManager.asset
=> implemented jump

Assets/GlitchEscape/Scenes/Testing/InteractionTankTest.unity
Fix objective ui scaling issue, hopefully, need tests
=> fix scaling issue(maybe)

Assets/GlitchEscape/Art/Items/PolyspherePetals.mat, Assets/GlitchEscape/Art/Items/PolysphereStand.mat, Assets/GlitchEscape/Art/PlayerAbilities/GlitchMaterial.mat, Assets/GlitchEscape/Prefabs/Enemies/ProjectileEnemy.prefab, Assets/GlitchEscape/Prefabs/Enemies/SlowSphereProj.prefab, Assets/GlitchEscape/Scenes/TestScenes/Enemy/ProjectileEnemyTest.unity, Assets/GlitchEscape/Scripts/Enemies/EnemyAttack.cs, Assets/GlitchEscape/Scripts/Enemies/EnemyController.cs, Assets/GlitchEscape/Scripts/Enemies/EnemyShoot.cs, Assets/GlitchEscape/Scripts/Enemies/Projectile.cs
Projectile prefab enemy will now fire multiple times with a cooldown.
=> Projectile Enemy Bug Fixes

Assets/Editor/GlitchEscape/Scripts/PlayerDashControllerInspector.cs, Assets/Editor/GlitchEscape/Scripts/PlayerDashControllerInspector.cs.meta, Assets/GlitchEscape/Config/Input/Input.cs, Assets/GlitchEscape/Config/Input/Input.inputactions, Assets/GlitchEscape/Prefabs/Player/NewPlayer Variant.prefab, Assets/GlitchEscape/Prefabs/Player/PlayerCameraRig.prefab, Assets/GlitchEscape/Scenes/Levels/Vertical_Platforming_Level.unity, Assets/GlitchEscape/Scenes/TestScenes/PlayerControlsTest.unity, Assets/GlitchEscape/Scenes/TestScenes/PlayerControlsTest.unity.meta, Assets/GlitchEscape/Scripts/Player/Abilities/PlayerAbility.cs, Assets/GlitchEscape/Scripts/Player/Abilities/PlayerAbility.cs.meta, Assets/GlitchEscape/Scripts/Player/All/PlayerController.cs, Assets/GlitchEscape/Scripts/Player/All/PlayerControls.cs, Assets/GlitchEscape/Scripts/Player/All/PlayerControls.cs.meta, Assets/GlitchEscape/Scripts/Player/Camera/PlayerCameraController.cs, Assets/GlitchEscape/Scripts/Player/Controls/PlayerInteractionController.cs, Assets/GlitchEscape/Scripts/Player/Controls/PlayerMovementController.cs, Assets/GlitchEscape/Scripts/Player/Mechanics/PlayerDashController.cs, Assets/GlitchEscape/Scripts/Test/PlayerControlsTest.cs, Assets/GlitchEscape/Scripts/Test/PlayerControlsTest.cs.meta, Assets/GlitchEscape/Scripts/Utility/Enforcements.cs
- managed to completely replace (or mostly replace) the existing PlayerInput + input actions system with `PlayerControls.cs`
- the previous system did not give us a reliable robust way to poll input (or detect if a button was pressed in an input callback!!!!), either due to a flawed design, or, more likely, having something horrifically wrong happen in the new input subsystem (ie. cancel actions not being called), which may have occurred (and was not detected) due to a lack of unit testing. Or, whoever designed this system is simply insane and it's behaving exactly as expected.
Either way:
- `PlayerControls.cs` gives you sane input you can query anywhere via a monobehavior singleton
- this includes basic, but fairly functional (and actually robust, unlike the recommended unity input …
=> Player input refactor + dash improvements

Assets/Editor/GlitchEscape/Scripts/PlayerDashControllerInspector.cs, Assets/GlitchEscape/Art/PlayerAbilities/GlitchMaterial.mat, Assets/GlitchEscape/Prefabs/Player/PlayerCameraRig.prefab, Assets/GlitchEscape/Scenes/Levels/Vertical_Platforming_Level.unity, Assets/GlitchEscape/Scripts/Player/Abilities/PlayerAbility.cs, ProjectSettings/EditorBuildSettings.asset
Added objectives to Vertical_Platforming_Level
More wall jumping sections and more damaging barriers in Vertical_Platforming_Level
=> Added objectives to Platforming Level with slight modifications to the level.

Assets/GlitchEscape/Sound/Abrupt.wav.meta, Assets/GlitchEscape/Sound/Ambience_Space.wav.meta, Assets/GlitchEscape/Sound/Bloop.wav.meta, Assets/GlitchEscape/Sound/Chains.wav.meta, Assets/GlitchEscape/Sound/Damage_Potentially.wav.meta, Assets/GlitchEscape/Sound/Dit.wav.meta, Assets/GlitchEscape/Sound/Doot.wav.meta, Assets/GlitchEscape/Sound/Drawn_Out_Alert.wav.meta, Assets/GlitchEscape/Sound/Explore.ogg.meta, Assets/GlitchEscape/Sound/Explore_Less_Sinister.ogg.meta, Assets/GlitchEscape/Sound/Main_item_get.mp3.meta, Assets/GlitchEscape/Sound/Maze_trigger_standing_on.mp3.meta, Assets/GlitchEscape/Sound/Ping.wav.meta, Assets/GlitchEscape/Sound/Potential..wav.meta, Assets/GlitchEscape/Sound/Potential_Distort.wav.meta, Assets/GlitchEscape/Sound/Soft_Alert.wav.meta, Assets/GlitchEscape/Sound/Some_Enemy_Sound.wav.meta, Assets/GlitchEscape/Sound/Sound_for..wav.meta, Assets/GlitchEscape/Sound/Sound_for_Softer.wav.meta, Assets/GlitchEscape/Sound/Sound_for_distort.wav.meta, Assets/GlitchEscape/Sound/Spiral.wav.meta, Assets/GlitchEscape/Sound/Static.wav.meta, Assets/GlitchEscape/Sound/Sweep.wav.meta, Assets/GlitchEscape/Sound/Weapon.wav.meta, Assets/GlitchEscape/Sound/Whirl.wav.meta
(add missing sound meta files that are constantly regenerating
themselves in unity)
=> add sound meta files

Assets/GlitchEscape/Scripts/Player/Controls/PlayerJumpController.cs
(set / override velocity if falling, ie. velocity < 0)
=> polish: improved double jump handling

Assets/GlitchEscape/Art/PlayerAbilities/GlitchMaterial.mat, Assets/GlitchEscape/Prefabs/Items/Polysphere.prefab, Assets/GlitchEscape/Scenes/Levels/Vertical_Main_Level.unity, Assets/GlitchEscape/Scenes/Levels/Vertical_Platforming_Level.unity, Assets/GlitchEscape/Scripts/Interaction/InteractablePolysphere.cs, Assets/GlitchEscape/Scripts/Interaction/InteractablePortal.cs, Assets/GlitchEscape/Scripts/Interaction/InteractableTank.cs
Changed [extract] to [Free hostage]
Changed [pick up] to [Collect Polysphere]
Changed [go through] to [Step through the portal]
Added polysphere holders to levels
=> Changed interaction text and added polysphere holders to levels

Assets/GlitchEscape/Prefabs/Player/PlayerCameraRig.prefab, Assets/GlitchEscape/Scripts/Interaction/SavePoint.cs, Assets/GlitchEscape/Scripts/Player/Abilities/PlayerAbility.cs, Assets/GlitchEscape/Scripts/Player/All/Player.cs, Assets/GlitchEscape/Scripts/Player/All/PlayerController.cs, Assets/GlitchEscape/Scripts/Player/Controls/PlayerMovementController.cs, Assets/GlitchEscape/Scripts/Player/Mechanics/MazeSwitch.cs, Assets/GlitchEscape/Scripts/Player/Mechanics/MazeSwitchController.cs, Assets/GlitchEscape/Scripts/Player/Mechanics/PlayerDashController.cs
- active bug; be warned (see commits)
=> player mechanic tweaks

Assets/GlitchEscape/Art/PlayerAbilities/GlitchMaterial.mat, Assets/GlitchEscape/Prefabs/Environment/TestLevel.prefab, Assets/GlitchEscape/Prefabs/Player/DialogNPCs.prefab, Assets/GlitchEscape/Scenes/Levels/Vertical_Main_Level.unity, Assets/GlitchEscape/Scenes/Levels/Vertical_Platforming_Level.unity
Added environmental assets to Vertical_Main_Level (trees, jellyfish, fog)
Added trees to Vertical_Platforming
Updated rabbit's textures
Fixed the portals not appearing after extracting all tanks
Level modifications to Vertical_Main_Level
=> Vertical levels polish

Assets/GlitchEscape/Prefabs/Player/PlayerCameraRig.prefab, Assets/GlitchEscape/Scenes/Levels/Vertical_Main_Level.unity
Fixed UI scale for polysphere
Fixed UI scale for dialog
Fixed UI scale for interaction(no more line warp)
Moved a jellyfish object outside UI
=> fixed ui scale problems

Assets/GlitchEscape/Prefabs/Player/PlayerCameraRig.prefab, Assets/GlitchEscape/Scenes/Levels/Hub_Level.unity, Assets/GlitchEscape/Scenes/Levels/Vertical_Main_Level.unity, Assets/GlitchEscape/Scripts/Player/All/Player.cs
New code is in Player.cs, disables camera and immediately re-enables it on respawn. Changed prefab settings for cinemachine brain.
=> fixed cinemachine respawn bug and camera collision

Assets/GlitchEscape/Art/Player/Animations/NewPlayerAnimController.controller, Assets/GlitchEscape/Art/Player/Animations/playerJumpStart.anim, Assets/GlitchEscape/Art/Player/Animations/playerJumpStart.anim.meta, Assets/GlitchEscape/Art/Player/NewPlayer.fbx.meta, Assets/GlitchEscape/Art/Player/OldPlayer.fbx.meta, Assets/GlitchEscape/Art/Player/PlayerPants.mat, Assets/GlitchEscape/Scenes/TestScenes/Animations/PlayerAnimationTest.unity
Merged the mesh. Changed the import smoothing settings. Update the animation test scenes.
Also updated the pants color
=> Player model merged

Assets/GlitchEscape/Scenes/Levels/Opening.unity, Assets/GlitchEscape/Scripts/UI/OpeningController.cs
also, the delay has a property to change in the inspector.
=> added autoplay to opening

Assets/GlitchEscape/Prefabs/Player/PlayerCameraRig.prefab, Assets/GlitchEscape/Scenes/TestScenes/MenuTest.unity, Assets/GlitchEscape/Scenes/TestScenes/MenuTest.unity.meta, Assets/GlitchEscape/Scripts/Player/All/VolumeController.cs, Assets/GlitchEscape/Scripts/Player/All/VolumeController.cs.meta, Assets/GlitchEscape/Scripts/UI/PauseMenuController.cs
Added settings in pause menu
Added music volume slider in settings
Added arrow highlighting for slider
=> Volume slider

Assets/GlitchEscape/Scenes/TestScenes/FragmentPickupTest.unity, Assets/GlitchEscape/Scripts/Agents/Player/Components/FragmentComponent.cs
the fragment total wasn't being set correctly, mb
=> fix for Fragments scene counting

Assets/GlitchEscape/Art/PlayerAbilities/GlitchMaterial.mat, Assets/GlitchEscape/Scenes/Levels/Third_Level.unity
-Removed the old spawners and replaced them with the new ones in Third_Level
=> Updated the projectile spawners in Third Level

Assets/GlitchEscape/Scripts/Agents/Player/Components/PlayerSpawnController.cs
=> fixed camera respawn bug

Assets/GlitchEscape/Art/UI/Animations/OrbAcquired.anim, Assets/GlitchEscape/Art/UI/Animations/OrbAcquired.anim.meta, Assets/GlitchEscape/Art/UI/visitor1 SDF.asset, Assets/GlitchEscape/Prefabs/Player/PlayerCameraRig.prefab, Assets/GlitchEscape/Scenes/Levels/SGDAEndCard.unity, Assets/GlitchEscape/Scenes/Levels/Vertical_Platforming_Level.unity, Assets/GlitchEscape/Scripts/Mechanics/Interaction/InteractablePortal.cs, Assets/GlitchEscape/Scripts/Mechanics/SceneLoading/Loader.cs, Assets/OrbUIController.cs, Assets/OrbUIController.cs.meta, ProjectSettings/EditorBuildSettings.asset
Added the activation of the portal once the player gets all 7 fragments. 
Known Issue:
-The portal text isn't working, not sure how long ago this bug was introduced
=> Demo win condition

Assets/GlitchEscape/Art/PlayerAbilities/GlitchMaterial.mat, Assets/GlitchEscape/Scenes/Levels/Tutorial/Tutorial_01_Movement.unity, Assets/GlitchEscape/Scenes/Levels/Tutorial/Tutorial_02_Advanced_Movement.unity, Assets/GlitchEscape/Scenes/Levels/Tutorial/Tutorial_03_Maze_Switch.unity
-Updated the text in the tutorial levels. (Now include both keyboard and controller inputs)
=> Updated tutorial text with controller inputs

Assets/GlitchEscape/Art/Enemies/GhostHand.blend.meta, Assets/GlitchEscape/Art/Enemies/enemy3s.blend.meta, Assets/GlitchEscape/Config/Input/Input.cs, Assets/GlitchEscape/Config/Input/Input.inputactions, Assets/GlitchEscape/Prefabs/Player/PlayerCameraRig.prefab, Assets/GlitchEscape/Scenes/TestScenes/MenuTest.unity, Assets/GlitchEscape/Scripts/Mechanics/PauseMenu/PauseMenuController.cs
Added keymap for Xbox controller to close the in-game menu with B button
Added functional FOV slider
Added non-functional camera sensitive slider and invert Y toggle.
* In order to make both of these setting functional, change of camera script base code is necessary( it is currently private and not updated with player config in runtime)
Example of changing it: 
add two variables in camera script
```
public void Update() {
var lookInput = PlayerControls.instance.lookInput;
freeLookCam.m_XAxis.Value = freeLookCam.m_XAxis.Value + lookInput.x * variableA * cameraTurnSpeed * Time.deltaTime;
freeLookCam.m_YAxis.Value = freeLookCam.m_YAxis.Value - lookInput.y * variableB * Time.deltaTime;
}
```
where variableA and variableB set to public and be able to modify from other script.
=> update menu settings

Assets/GlitchEscape/Prefabs/Environment/SkyObject.prefab, Assets/GlitchEscape/Prefabs/Environment/SkyObject.prefab.meta, Assets/GlitchEscape/Scenes/Levels/Hub_Level.unity, Assets/GlitchEscape/Scenes/TestScenes/BuildingModsTest/Building Mods Test.unity, Assets/GlitchEscape/Scripts/Environment/Floater.cs, Assets/GlitchEscape/Scripts/Environment/Floater.cs.meta
Added Sky Object
Added a script that makes things float
Updated the Building Mods Test Scene
Discarded the hub level updates (sky objects) because it can't merge.
=> Sky Object & Script Added

Assets/Editor/GlitchEscape/Scripts/MazeControllerEditor.cs, Assets/Editor/GlitchEscape/Scripts/MazeControllerEditor.cs.meta, Assets/GlitchEscape/Prefabs/Environment/MazeTrigger.prefab, Assets/GlitchEscape/Prefabs/Environment/TestLevel.prefab, Assets/GlitchEscape/Scenes/Levels/Third_Level.unity, Assets/GlitchEscape/Scripts/Agents/Player/Data/PlayerConfig.cs, Assets/GlitchEscape/Scripts/Mechanics/MazeSwitching/MazeSwitch.cs, Assets/GlitchEscape/Scripts/Mechanics/MazeSwitching/PlayerMazeController.cs, Assets/GlitchEscape/Scripts/Mechanics/MazeSwitching/SceneMazeController.cs, ProjectSettings/TagManager.asset
- fix broken maze triggers
- MazeSwitch.cs refactored to use InteractiveObject (and prefab updated)
- SceneMazeController.cs cleaned up and simplified
- added custom editor code so maze switching will happen if you switch active mazes from the editor :)
=> Cleanup + fix maze controller impl

Assets/GlitchEscape/Art/PlayerAbilities/GlitchMaterial.mat, Assets/GlitchEscape/Scripts/Player/All/PlayerShadow.cs
made landing indicator persist across scenes
=> fixed landing indicator persistance bug

Assets/GlitchEscape/Scripts/Agents/Player/Abilities/PlayerManifestAbility.cs, Assets/GlitchEscape/Scripts/Agents/Player/Abilities/PlayerShootAbility.cs, Assets/GlitchEscape/Scripts/Agents/Player/Agent/Player.cs, Assets/GlitchEscape/Scripts/Agents/Player/Controls/PlayerControls.cs, Assets/GlitchEscape/Scripts/Test/PlayerControlsTest/PlayerControlsTest.cs
The player can no longer use the shoot and manifest abilities
=> Remove old abilities

Assets/GlitchEscape/Scripts/Player/All/PlayerShadow.cs, Assets/GlitchEscape/Scripts/Utility/LayerMasks.cs, Assets/GlitchEscape/Scripts/Utility/LayerMasks.cs.meta
unparanted the landing indicator from player so it is now in global space
im hoping, praying, that this is the last major bugfix for the player jump
=> Fixed clipping landing issue

Assets/GlitchEscape/Dialog/HubDialog.yarn, Assets/GlitchEscape/Scenes/Levels/Hub_Level.unity, Assets/GlitchEscape/Scripts/Agents/Player/Components/PlayerDialogController.cs
Parts of previous yarn file got overwritten so I added missing parts back in again.
=> Updated yarn file for hostage cutscenes

Assets/GlitchEscape/Art/PlayerAbilities/GlitchMaterial.mat, Assets/GlitchEscape/Prefabs/Environment/TestLevel.prefab, Assets/GlitchEscape/Scenes/Levels/Tutorial/ScenePrefabs/SCN_Tut03_MazeSwitch.prefab, Assets/GlitchEscape/Scenes/Levels/Tutorial/ScenePrefabs/SCN_Tut04_Fragments.prefab, Assets/GlitchEscape/Scenes/Levels/Tutorial/Tutorial_04_Fragment.unity, Assets/GlitchEscape/Scripts/Agents/Player/UI/PlayerHUD/PlayerStatsView.cs
Redid all 5 levels (tutorial 3 & 4, vertical platform, vertical main, and third level) that have the glitch maze. For levels with prefabs, applied script to prefabs
=> Redid platform UI on the prefabs

Assets/GlitchEscape/Prefabs/Environment/BuildingDecor/Brush.prefab, Assets/GlitchEscape/Prefabs/Environment/BuildingDecor/Lamp.prefab, Assets/GlitchEscape/Prefabs/Environment/BuildingDecor/LightBubble.prefab
Added Collisions for the lighting props
=> Added Collisions to Props

Assets/GlitchEscape/Scripts/Player/Controls/CameraModeController.cs
it was actually simpler than i thought, it looks good enough as is with the lerp function
=> added smooth follow to camera reset

Assets/GlitchEscape/Prefabs/Player/PlayerCameraRig.prefab, Assets/GlitchEscape/Scripts/Agents/Player/Components/PlayerDialogController.cs, Assets/GlitchEscape/Scripts/Agents/Player/UI/PlayerHUD/PlayerStatsView.cs, Assets/GlitchEscape/Scripts/Mechanics/Fragments/FragmentWorldVFX/FragmentWorldVFX.cs, Assets/GlitchEscape/Scripts/Utility/FPSCounter.cs
- fixed bug that was tanking framerate in the game / at runtime due to not caching references and thus calling FindObject<T>() multiple times per frame (note: this is extremely expensive and was adding ~10ms of latency on frame updates, which is more than enough to tank the framerate below 60hz even on capable hardware)
- fixed bugs + tweaked things to improve editor speed + responsiveness (which currently is / was very poor due to a combination of custom editor scripts interacting in slightly unanticipated ways and forcing some expensive updates to get run continuously)
=> Performance fixes

Assets/GlitchEscape/Scripts/Mechanics/Music/MusicController.cs
music wasn't looping correctly before, fixed now
=> music should now loop correctly

Assets/GlitchEscape/Scripts/Agents/Player/Abilities/PlayerJumpAbility.cs
should fix infinite jumping and should reset jumps correctly
=> Wall jump fix

Assets/GlitchEscape/Scripts/Agents/Player/Abilities/PlayerJumpAbility.cs
Reverts glitch-escape/glitch-escape#401
Unintended overwrites.
=> Revert "Wall jump fix"

Assets/GlitchEscape/Art/PlayerAbilities/GlitchMaterial.mat, Assets/GlitchEscape/Config/Dialog/CutSceneDialog.asset, Assets/GlitchEscape/Config/Dialog/DialogConfig.asset, Assets/GlitchEscape/Config/Dialog/HostageDialog.asset, Assets/GlitchEscape/Scenes/Levels/Third_Level.unity
=> Changed npc materials

Assets/GlitchEscape/Config/Player/PlayerMechanicConfigs/RotationPuzzleConfig.asset
this should fix the rotation bug
=> fixed rotation puzzle break

Assets/GlitchEscape/Prefabs/Player/PlayerCameraRig.prefab, Assets/GlitchEscape/Prefabs/Player/PlayerHUD.prefab, Assets/GlitchEscape/Scripts/Mechanics/Fragments/FragmentUI.cs
=> Fragment fixes

Assets/GlitchEscape/Scripts/Agents/Player/Abilities/PlayerJumpAbility.cs
player should no longer infinitely jump... this time for real
=> re-fixed wall jump infinite jump
